Transform: AWS::Serverless-2016-10-31
Resources:
  ProductsGetFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs10.x
      CodeUri: ./src/
      Environment:
        Variables:
          TABLE_NAME: products
      Events:
          GetProduct:
              Type: Api
              Properties:
                  Path: /products/{id}
                  Method: GET
  ProductsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
